# Server configuration
spring.application.name=link.whoa
server.port=8844

spring.profiles.active=dev

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.contexts=dev

# Database configuration (Writer - Default)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5444}/${POSTGRES_DB:link_whoa}
spring.datasource.username=${DB_USER:whoa}
spring.datasource.password=${DB_PASSWORD:whoa}
spring.datasource.driver-class-name=org.postgresql.Driver

# Database configuration (Reader - Optional Fallback)
app.datasource.reader.url=${DB_READER_URL:}
app.datasource.reader.username=${DB_READER_USER:}
app.datasource.reader.password=${DB_READER_PASSWORD:}

# Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cache configuration
app.cache.urls.initial-capacity=100
app.cache.urls.maximum-size=500
app.cache.urls.expire-after-write=10m

# Analytics Settings
app.analytics.refresh-interval-ms=10000
