apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "link-whoa-qa.fullname" . }}-config-qa
  labels:
    {{- include "link-whoa-qa.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  POSTGRES_DB: {{ .Values.config.database.name | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
