apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "link-whoa-qa.fullname" . }}-pdb-qa
  labels:
    {{- include "link-whoa-qa.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "link-whoa-qa.selectorLabels" . | nindent 4 }}
