apiVersion: v1
kind: Service
metadata:
  name: {{ include "link-whoa-qa.fullname" . }}-qa
  labels:
    {{- include "link-whoa-qa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "link-whoa-qa.selectorLabels" . | nindent 4 }}
