/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#8f909e",
        "background": "#131313",
        "surface": "#131313",
        "surface-dim": "#131313",
        "tertiary": "#ffb2be",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#004650",
        "on-secondary-fixed-variant": "#004e59",
        "secondary-container": "#00bcd4",
        "outline-variant": "#454652",
        "on-background": "#e5e2e1",
        "on-primary-container": "#cacfff",
        "secondary-fixed-dim": "#44d8f1",
        "tertiary-container": "#b50048",
        "on-surface-variant": "#c5c5d4",
        "secondary-fixed": "#a1efff",
        "tertiary-fixed": "#ffd9de",
        "on-tertiary-fixed": "#400014",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#293ca0",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#900038",
        "surface-variant": "#353534",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#660025",
        "secondary": "#44d8f1",
        "surface-container-highest": "#353534",
        "error-container": "#93000a",
        "on-primary-fixed": "#00105c",
        "inverse-primary": "#4355b9",
        "primary-container": "#3f51b5",
        "on-primary": "#08218a",
        "tertiary-fixed-dim": "#ffb2be",
        "primary": "#bac3ff",
        "primary-fixed-dim": "#bac3ff",
        "surface-tint": "#bac3ff",
        "on-error": "#690005",
        "primary-fixed": "#dee0ff",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#00363e",
        "on-tertiary-container": "#ffc3cb",
        "on-secondary-fixed": "#001f25",
        "surface-container": "#201f1f",
        "surface-bright": "#393939",
        "error": "#ffb4ab"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
