name: PR Check

on:
  pull_request:
    branches: [ "master", "feature/*" ]

jobs:
  format-checker:
    name: Format Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'
      - name: Check Formatting
        run: ./gradlew ktlintCheck

  frontend-checker:
    name: Frontend Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install dependencies
        working-directory: ./ui
        run: npm ci
      - name: Lint Frontend
        working-directory: ./ui
        run: npm run lint --if-present

  build-test-and-artifact:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'
      
      - name: Build and Test
        run: ./gradlew build
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/test/TEST-*.xml'
          require_tests: true
          annotate_notice: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ci.Dockerfile
          push: false
          tags: whoa-app:pr-${{ github.event.pull_request.number }}
          outputs: type=docker,dest=/tmp/whoa-app.tar

      - name: Upload Docker Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-artifact-pr-${{ github.event.pull_request.number }}
          path: /tmp/whoa-app.tar
          retention-days: 90
